### PR TITLE
Add cluster mgmt and accounts mgmt packages

### PR DESCRIPTION
**Pull request by Hyperkid123**
cc @wtrocki 

The [cluster management](https://api.openshift.com/?urls.primaryName=Clusters%20management%20service) and [accounts management](https://api.openshift.com/?urls.primaryName=Accounts%20management%20service) clients are required for new application-services-ui feature

### CODE REVIEW

**Comment by wtrocki** [comment]
Can I we get more context? 
We do have account management api already but it has been reduced in size. Cluster management - It might be worth checking if there is SDK for it (certainly there is UI already)

**Comment by Hyperkid123** [comment]
> Can we get more context? We do have account management api already but it has been reduced in size. Cluster management - It might be worth checking if there is SDK for it (certainly there is UI already)

@wtrocki ofc

Our team was asked to help out and implement new features into the RHODS (data science) UI (we do not own that UI we are just helping because the RHODS team does not FE developers). As a part of that we require two new endpoints to get the necessary data:
- `https://api.openshift.com/api/accounts_mgmt/v1/subscriptions`
- `https://api.openshift.com/api/clusters_mgmt/v1/clusters/{cluster.cluster_id}/addon_inquiries`

For development, I have simple `fetch` placeholders. I was asking Riccardo what is the preferred way of calling the API and that's when he told me about the SDK. I scanned through the existing SDK and AFAIK none of them supports the APIs I need. I took a closer look at the existing ams package and I yeah its the same. So I can scrap that one.

But still need the clusters package.

**Comment by wtrocki** [comment]
Apologies. I have missed your reply.
> But still need the clusters package.

That is covered by OCM-SDK (JS and GO). 
Managed services are focused around Kafka + friends thus we do not want to bring some low level/not end user relevant SDKs.

**Comment by Hyperkid123** [comment]
@wtrocki do you have a link for the OCM-SDK?

**Pull request closed without merging**
