### PR TITLE
Fix kafka-instance-sdk build

### PR DESCRIPTION
**Pull request by jomarko**

### CODE REVIEW

**Comment by dimakis** [comment]
Hey @jomarko , thanks for the PR. I'm just looking to see what you did here? re-added the correct oas file for `kafka-admin-rest`?

**Comment by jomarko** [comment]
I think I did this:
- `scripts/fetch_api.sh https://raw.githubusercontent.com/bf2fc6cc711aee1a0c2a/kafka-admin-api/main/kafka-admin/.openapi/kafka-admin-rest.yaml`
- `yarn generate`
- `yarn build` to check its working now

**Comment by dimakis** [comment]
@jomarko The failed builds here stem from some legacy code, before the `bf2...` org was open, a token was used to fetch the OAS files. This token the other day, causing the OAS files pulled to be replaced by `404: not found`.
When the generate script runs it fails as there is no OAS files to generate from. 

I fixed this issue on Monday / Tuesday so all SDKs are back functional. 

In regards your comment on generating SDKs per OAS file (individual project) yes, this is something that is in our backlog and will be implemented as we move to a new `core` / monorepo style repo for the SDKs. This is currently timetabled for the next or subsequent sprint. 

Your help and time that you've spent in this area is greatly appreciated. Thank you 😄

**Comment by jomarko** [comment]
Thank you @dimakis . reading your comment https://github.com/redhat-developer/app-services-sdk-js/pull/522#issuecomment-1240360745 I am closing this #522 PR

**Pull request closed without merging**
