### PR TITLE
feat: update smartevents to v2

### PR DESCRIPTION
**Pull request by dimakis**
Updating smartevents mgmr to use v2 of their openapi spec file

the v2 is already present in the [repo](https://github.com/redhat-developer/app-services-sdk-js/blob/main/.openapi/smartevents_mgmt_v2.yaml)

### CODE REVIEW

**Comment by jackdelahunt** [comment]
so we are upgrading the api in the SDK, are we planing this for the other SDKs?

**Comment by dimakis** [comment]
> @dimakis
> 
> So we are upgrading the api in the SDK, are we planing this for the other SDKs?

in what regard is that? if the other APIs are bumping their version?

This is coming from a request I got to bump the SDK version for smartevents. They want the same package, just different version so this seems the most seamless way to do so

**Comment by jackdelahunt** [comment]
> in what regard is that? if the other APIs are bumping their version?

Well if they want to. bumb the version of this dont we want our. sdks in sync shouldnt this also be applied to other SDKs. But maybe i am misunderstanding.

**Comment by dimakis** [comment]
> > in what regard is that? if the other APIs are bumping their version?
> 
> Well if they want to. bumb the version of this dont we want our. sdks in sync shouldnt this also be applied to other SDKs. But maybe i am misunderstanding.

sorry, you mean other languages? yes indeed we do that is correct. 
Thats what I was hoping to achieve by "assigning" this to you last week. I've never used the assign thing before though so not sure if you got it or not 😅

**Comment by jackdelahunt** [comment]
Oh I see that you okay no problem will merge this, should we not re-generate sdk in pr aswell?

**Comment by dimakis** [comment]
> Oh I see that you okay no problem will merge this, should we not re-generate sdk in pr aswell?

I was going to do that manually. Usually this is automated as per https://github.com/redhat-developer/app-services-sdk-js/actions/runs/3490454820
I've not changed the Open API spec file like this before though so I was just going to do a manual regen of the SDKs before releasing just to make sure.

**Review by jackdelahunt — APPROVED** [review]
LGTM 👍

**Pull request merged**
