### PR TITLE
Add sorting for  consumer groups by group id

### PR DESCRIPTION
**Pull request by suyash-naithani**

### CODE REVIEW

**Comment by wtrocki** [comment]
1. Verified locally.

Side note: We have started with mock as form of tool that can help us to do things that we could not do with backend (like kafk)
but recently mock became more critical element of the development for the teams and getting more and more advanced features. This was never intended to happen but it is great statement that our teams rely on mock for daily usage.

AMAZING WORK!

**Comment by wtrocki** [comment]
Will release today along with other fixes

**Comment by suyash-naithani** [comment]
@wtrocki It's great to see the mock getting better with each day. Thanks @wtrocki . 
Could you make the release sometime tomorrow? I might have another PR I'd like to push , to make it possible to increase the partitions size

**Comment by wtrocki** [comment]
@suyash-naithani I have no pressure to release so will wait for ping.

**Pull request merged**
