### PR TITLE
fix: ams marketplace changes

### PR DESCRIPTION
**Pull request by rkpattnaik780**
Follow up to [app-services-sdk-go#452](https://github.com/redhat-developer/app-services-sdk-go/pull/452).

### CODE REVIEW

**Comment by wtrocki** [comment]
Looks good. Lets release this as alpha

**Comment by rkpattnaik780** [comment]
Relased [0.34.2-alpha1](https://github.com/redhat-developer/app-services-sdk-js/releases/tag/0.34.2-alpha1)

**Comment by rkpattnaik780** [comment]
Does the java-sdk have any requirement for `ams`?

**Comment by wtrocki** [comment]
I have created issue to cover AMS SDK into Java SDK. For now we can ignore it.

**Pull request merged**
